### ISSUE TITLE
Using a non-placeable block crashes the server

### ISSUE THREAD

**Issue by seijikun** [mc-server/WorldEdit#84] opened 2015-10-24 22:03 UTC
When using non-placeable blocks as fill-material, the server crashes.
What I tried:
`//hcyl brick 6`
or equally
`//hsphere brick 6`

**Comment by madmaxoft** [comment] 2015-10-30 13:37
This is basically a duplicate of #26

**Comment by NiLSPACE** [comment] 2015-10-30 13:46
Pretty much

**Closed by NiLSPACE** 2015-10-30 13:46 UTC
